version: "3.4"

services:
    load-balance:
        image: nginx:latest
        container_name: load-balance
        volumes:
            - ./nginx:/etc/nginx/conf.d/
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        networks:
            - rupadana-my-id
        ports:
            - "80:80"
            - "443:443"
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email rupadanawayan@gmail.com -d test.rupadana.my.id --agree-tos
networks:
    rupadana-my-id:
        driver: bridge
        external: true
