version: "3.4"

services: 
    load-balance:
        image: nginx:latest
        container_name: load-balance
        volumes: 
            - ./nginx:/etc/nginx/conf.d/
        networks: 
            - yours-network
        ports: 
            - "80:80"
            - "443:443"



networks: 
    yours-network:
        driver: bridge
        external: true